* Vim-OrgMode

  https://secure.travis-ci.org/sotte/vim-orgmode.png?branch=master

  Text outlining and task management for Vim based on Emacs' Org-Mode
  ([[http://orgmode.org/]]).

  The idea for this plugin was born by listening to the Floss Weekly podcast
  introducing Emacs Org-Mode (http://twit.tv/floss136). Org-Mode has a lot of
  strong features like folding, views (sparse tree) and scheduling of tasks.
  These are completed by hyperlinks, tags, todo states, priorities aso.

  Vim-orgmode aims at providing the same functionality for Vim and for command
  line tools*.

  *for command line tools and other programs a library named liborgmode is
   provided. It encapsulates all functionality for parsing and modifying
   Org-Mode files.

** Features
   vim-orgmode is still very young but already quite usable. Here is a short
   list of the already supported features:

   - Cycle visibility of headings
   - Navigate between headings
   - Edit the structure of the document: add, move, promote, denote headings
     and more
   - Hyperlinks within vim-orgmode and outside (files, webpages, etc.)
   - TODO list management
   - Tags for headings
   - Basic date handling
   - Export (via emacs)

   More features are coming...

* License
  Information about the license are found in the file LICENSE.

* Installation and Usage
  Installation and usage instructions are found in the file [[doc/orgguide.txt][doc/orgguide.txt]].
